name: Project Set-up, Formatting, Linting, Building

on:
    pull_request:
        branches: ['**']

jobs:
    build-checks:
        name: Set-up, Lint, Format and Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5

            - name: Setup node version
              uses: actions/setup-node@v6
              with:
                  node-version-file: '.nvmrc'

            - name: Install Dependencies
              run: npm install

            - name: Formatting the code
              run: npm run prettier

            - name: Linting the code
              run: npm run lint

            - name: Type checkout
              run: npm run ts:check

            - name: Build project
              run: npm run build
